[tox]
envlist = py314
skip_missing_interpreters = true
skipsdist=True

[testenv]
allowlist_externals = rm
commands =
    {envpython} -m pip -q install ../../../checkbox-ng
    # Required because this provider depends on checkbox-support parsers & scripts
    {envpython} -m pip -q install ../../../checkbox-support
    rm -f /var/tmp/checkbox-providers-develop/checkbox-provider-resource.provider
    rm -f /var/tmp/checkbox-providers-develop/checkbox-provider-base.provider
    rm -f /var/tmp/checkbox-providers-develop/checkbox-provider-certification-client.provider
    rm -f /var/tmp/checkbox-providers-develop/checkbox-provider-certification-server.provider
    rm -f /var/tmp/checkbox-providers-develop/checkbox-provider-oem.provider
    # Install all providers in develop mode to make sure everything works fine
    {envpython} ../../../providers/resource/manage.py develop
    {envpython} ../../../providers/base/manage.py develop
    {envpython} ../../../providers/certification-client/manage.py develop
    {envpython} ../../../providers/certification-server/manage.py develop
    {envpython} manage.py develop
    {envpython} manage.py validate
    {envpython} -m coverage run manage.py test
    {envpython} -m coverage report
    {envpython} -m coverage xml
    rm -f /var/tmp/checkbox-providers-develop/checkbox-provider-resource.provider
    rm -f /var/tmp/checkbox-providers-develop/checkbox-provider-base.provider
    rm -f /var/tmp/checkbox-providers-develop/checkbox-provider-certification-client.provider
    rm -f /var/tmp/checkbox-providers-develop/checkbox-provider-certification-server.provider
    rm -f /var/tmp/checkbox-providers-develop/checkbox-provider-oem.provider

[testenv:py314]
deps =
    pip
    flake8
    coverage == 7.10.6
    pep8-naming
    pyserial
    natsort == 8.0.2
    requests == 2.31.0
    urwid == 2.6.10
    Jinja2 == 3.1.6
    MarkupSafe == 3.0.3
    XlsxWriter == 3.1.9
    tqdm == 4.66.2
    pyparsing == 3.1.1
    distro == 1.9.0
    PyYAML == 6.0.3
