name: checkbox18
summary: Checkbox runtime and public providers
description: "Checkbox runtime and public providers"
grade: stable
confinement: strict

version: '2.5'

base: core18

# Don't forget to add a new slot if a new provider part is added in the parts
# section below.
slots:
  provider-resource:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-resource
  provider-checkbox:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-base
  provider-snappy:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-snappy
  provider-docker:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-docker
  provider-tpm2:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-tpm2
  provider-engineering-tests:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-engineering-tests
  provider-sru:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-sru
  provider-gpgpu:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-gpgpu
  provider-certification-client:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-certification-client
  provider-certification-server:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-certification-server
  checkbox-runtime:
    interface: content
    read:
      - /

package-repositories:
  - type: apt
    ppa: hardware-certification/public

parts:
################################################################################
# Upstream: https://kernel.ubuntu.com/git/hwe/fwts.git/plain/snapcraft.yaml
  fwts:
    source-tag: "V23.01.00"
    source-depth: 1
    plugin: autotools
    source: git://kernel.ubuntu.com/hwe/fwts
    stage-packages:
      - libfdt1
      - libbsd0
      - libpci3
    build-packages:
      - gcc
      - make
      - autoconf
      - automake
      - libtool
      - libjson-c-dev
      - flex
      - bison
      - dh-autoreconf
      - libglib2.0-dev
      - libfdt-dev
      - libbsd-dev
################################################################################
# Upstream: https://kernel.ubuntu.com/git/cking/stress-ng.git/plain/snap/snapcraft.yaml
  stress-ng:
    source-tag: "V0.15.04"
    source-depth: 1
    plugin: make
    source: https://github.com/ColinIanKing/stress-ng.git
    make-parameters:
      - STATIC=1
    build-packages:
      - gcc
      - make
      - zlib1g-dev
      - libbsd-dev
      - libgcrypt20-dev
      - libkeyutils-dev
      - libapparmor-dev
      - libaio-dev
      - libcap-dev
      - libsctp-dev
      - libatomic1
      - libjudy-dev
      - libjpeg-dev
      - libglvnd-dev
      - libgbm-dev
      - libxxhash-dev
    after: [fwts]
################################################################################
# Upstream: https://kernel.ubuntu.com/git/cking/snapcraft-snaps.git/tree/acpica/snapcraft.yaml
  acpi-tools:
    source-tag: "R10_20_22"
    source-depth: 1
    plugin: make
    source: https://github.com/acpica/acpica.git
    build-packages:
      - gcc
      - make
      - bison
      - flex
    prime:
      - usr/bin/
    after: [stress-ng]
################################################################################
  checkbox-support:
    plugin: python
    source: checkbox-support
    source-type: local
    stage-packages:
      - python3-requests-unixsocket
      - python3-systemd
    python-packages:
      - pynmea2
      - pybluez
    build-packages:
      - libbluetooth-dev
      - python3-dev
    after: [acpi-tools]
    override-stage: |
      snapcraftctl stage
      sed -i 's|except OSError:  # Command not found|except subprocess.CalledProcessError:  # Command not found|g' lib/python3.*/site-packages/distro/distro.py
################################################################################
  checkbox-ng:
    plugin: python
    source: checkbox-ng
    source-type: local
    build-packages:
      - zlib1g-dev
      - build-essential
    stage-packages:
      - python3-markupsafe
      - python3-jinja2
      - python3-packaging
      - python3-padme
      - python3-requests-oauthlib
      - python3-urwid
      - python3-xlsxwriter
    python-packages:
      - tqdm
    after: [checkbox-support]
################################################################################
  checkbox-provider-resource:
    plugin: dump
    source: providers/resource
    source-type: local
    stage-packages:
      - cpu-checker
      - dpkg
      - dmidecode
      - libjson-xs-perl
      - pciutils
      - python3-requests-unixsocket
      - smartmontools
    override-build: |
      cd src && autoreconf -i && cd -
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.8/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      for path in $(find "$SNAPCRAFT_STAGE/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-resource --root="$SNAPCRAFT_PART_INSTALL"
    build-packages:
      - autoconf
      - automake
      - libnl-3-dev
      - libnl-genl-3-dev
      - pkg-config
    after: [checkbox-ng]
################################################################################
  checkbox-provider-base:
    plugin: dump
    source: providers/base
    source-type: local
    override-build: |
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.8/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      for path in $(find "$SNAPCRAFT_STAGE/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-base --root="$SNAPCRAFT_PART_INSTALL"
    stage-packages:
      - bc
      - bluez-tests
      - bonnie++
      - cryptsetup-bin
      - dbus
      - debsums
      - dmidecode
      - dmsetup
      - efibootmgr
      - ethtool
      - freeipmi-tools
      - fswebcam
      - gir1.2-cheese-3.0
      - gir1.2-clutter-1.0
      - gir1.2-gst-plugins-base-1.0
      - gir1.2-gudev-1.0
      - gnome-screenshot
      - gstreamer1.0-tools
      - gstreamer1.0-pulseaudio
      - on amd64: [hdapsd] # optional as not available for arm
      - hdparm
      - i2c-tools
      - ipmitool
      - iperf
      - iperf3
      - iw
      - jq
      - kmod
      - libasound2
      - libcap2-bin
      - libfdt1
      - lsb-release
      - lshw
      - mesa-utils
      - mokutil
      - net-tools
      - nmap
      - nux-tools
      - nvme-cli
      - obexftp
      - parted
      - pciutils
      - pulseaudio-utils
      - pyotherside
      - python3-dbus
      - python3-evdev
      - python3-gi
      - python3-natsort
      - python3-psutil
      - python3-serial
      - python3-yaml
      - qml-module-qtquick-controls
      - qml-module-qtquick-layouts
      - qmlscene
      - smartmontools
      - usbutils
      - util-linux
      - uuid-runtime
      - wget
      - wmctrl
      - xz-utils
    build-packages:
      - libasound2-dev
      - libcap-dev
    organize:
      usr/lib/lib*.so*: usr/lib/$SNAPCRAFT_ARCH_TRIPLET/
    after: [checkbox-provider-resource]
################################################################################
  checkbox-provider-docker:
    plugin: dump
    source: providers/docker
    source-type: local
    override-build: |
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.8/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      for path in $(find "$SNAPCRAFT_STAGE/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-docker --root="$SNAPCRAFT_PART_INSTALL"
    stage-packages:
      - apache2-utils
    after: [checkbox-provider-base]
################################################################################
  checkbox-provider-tpm2:
    plugin: dump
    source: providers/tpm2
    source-type: local
    override-build: |
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.8/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      for path in $(find "$SNAPCRAFT_STAGE/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-tpm2 --root="$SNAPCRAFT_PART_INSTALL"
    after: [checkbox-provider-docker]
################################################################################
  checkbox-provider-sru:
    plugin: dump
    source: providers/sru
    source-type: local
    override-build: |
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.8/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      for path in $(find "$SNAPCRAFT_STAGE/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-sru --root="$SNAPCRAFT_PART_INSTALL"
    after: [checkbox-provider-tpm2, tpm2-tools-3]
################################################################################
  checkbox-provider-gpgpu:
    plugin: dump
    source: providers/gpgpu
    source-type: local
    override-build: |
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.8/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      for path in $(find "$SNAPCRAFT_STAGE/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-gpgpu --root="$SNAPCRAFT_PART_INSTALL"
    after: [checkbox-provider-sru]
################################################################################
  checkbox-provider-certification-client:
    plugin: dump
    source: providers/certification-client
    source-type: local
    override-build: |
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.8/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      for path in $(find "$SNAPCRAFT_STAGE/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-certification-client --root="$SNAPCRAFT_PART_INSTALL"
    after: [checkbox-provider-gpgpu]
################################################################################
  checkbox-provider-certification-server:
    plugin: dump
    source: providers/certification-server
    source-type: local
    override-build: |
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.8/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      for path in $(find "$SNAPCRAFT_STAGE/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-certification-server --root="$SNAPCRAFT_PART_INSTALL"
    after: [checkbox-provider-certification-client]
################################################################################
  # This module is a dependency for the job gpio/gpiomem_loopback_pairs_{model}
  # in checkbox-provider-snappy only available in pypi and so can't be addded
  # to stage-packages
  rpi-support-libs:
    plugin: python
    python-packages:
      - RPi.GPIO
      - picamera
    build-environment:
      - READTHEDOCS: 'True'
  rpi-ppa:
    plugin: nil
    override-pull: |
      sudo add-apt-repository ppa:sylvain-pineau/ppa-rpi
      sudo apt-get update
    build-packages:
      - software-properties-common
  rpi-support-binaries:
    after: [rpi-ppa]
    plugin: nil
    stage-packages:
      - on armhf:
        - libraspberrypi0
      - on arm64:
        - libraspberrypi0
    organize:
      usr/lib/lib*.so: usr/lib/$SNAPCRAFT_ARCH_TRIPLET/
################################################################################
  lk-boot-env:
    plugin: nil
    source: .
    override-pull: |
      snapcraftctl pull
      wget https://raw.githubusercontent.com/snapcore/snapd/master/include/lk/snappy_boot_common.h
      wget https://github.com/snapcore/snapd/raw/master/include/lk/snappy_boot_v1.h
      wget https://raw.githubusercontent.com/kubiko/if6640-gadget/18/snap-boot-sel/lk-boot-env.c
    build-packages:
      - wget
      - on amd64 to armhf:
        - gcc-arm-linux-gnueabihf:amd64
      - on amd64 to arm64:
        - gcc-aarch64-linux-gnu:amd64
    override-build: |
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin
      if [ "${SNAPCRAFT_ARCH_TRIPLET}" = "arm-linux-gnueabihf" ]; then
          arm-linux-gnueabihf-gcc lk-boot-env.c -I/usr/include/ -Iapp/aboot -o ${SNAPCRAFT_PART_INSTALL}/bin/lk-boot-env
      elif [ "${SNAPCRAFT_ARCH_TRIPLET}" = "aarch64-linux-gnu" ]; then
          aarch64-linux-gnu-gcc lk-boot-env.c -I/usr/include/ -Iapp/aboot -o ${SNAPCRAFT_PART_INSTALL}/bin/lk-boot-env
      else
          # native build
          gcc lk-boot-env.c -I/usr/include/ -Iapp/aboot -o ${SNAPCRAFT_PART_INSTALL}/bin/lk-boot-env
      fi
################################################################################
  tpm2-tss:
    plugin: autotools
    source: https://github.com/tpm2-software/tpm2-tss
    source-type: git
    source-tag: "1.4.0"
    configflags:
      - --enable-unit
    build-packages:
      - autoconf
      - autoconf-archive
      - libtool
      - gcc
      - g++
      - libc6-dev
    prime:
      - -include
    # Keep this, fwts builds are somehow affected by staged libs if not built
    # first hence the after clause in tpm2-tss-1.4.
    after: [fwts]
################################################################################
  tpm2-tools-3:
    plugin: autotools
    source: https://github.com/tpm2-software/tpm2-tools
    source-type: git
    source-tag: "3.0.4"
    configflags:
      - --enable-unit
      - --with-tcti-device
    build-packages:
      - autoconf
      - autoconf-archive
      - automake
      - pkg-config
      - libcmocka-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libtool
      - python-yaml
    stage-packages:
      - try: [libcurl4]
      - else: [libcurl3]
    prime:
      - -include
    after: [tpm2-tss]
    override-pull: |
      snapcraftctl pull
      # https://github.com/tpm2-software/tpm2-tools/issues/908
      sed -i 's|LIBMARSHAL_CFLAGS = \\|LIBMARSHAL_CFLAGS = |g' Makefile.am
      sed -i 's|-DALG_ECMQV=1||g' Makefile.am
################################################################################
  parts-meta-info:
    plugin: nil
    override-build: |
      snapcraftctl build
      echo $PWD
      ls -1 -d ../../*
      for p in `ls -d ../../*`; do
          if [ -d $p/src ]; then
            (cd $p/src
                if [ -d $p/src/.git ]; then
                    (echo `basename $p`\: && git show --pretty=format:"%h%d %aN %ci%n%s%n" -q ; echo ) >> $SNAPCRAFT_PART_INSTALL/parts_meta_info
                fi # for additional `source-type` support, elif them here
            )
          fi
      done
    after: [checkbox-provider-certification-server]
################################################################################
  common-config:
    plugin: dump
    source: config/
