[tox]
envlist = py35
skip_missing_interpreters = true
skipsdist=True

[testenv]
allowlist_externals = bash
commands =
    {envpython} -m pip -q install ../../checkbox-ng
    {envpython} -m pip -q install ../../checkbox-support
    bash -c "for provider in ../*; do {envpython} $provider/manage.py develop -f; done"
    {envpython} manage.py validate
    {envpython} -m coverage run manage.py test
    {envpython} -m coverage report
    {envpython} -m coverage xml
setenv = PROVIDERPATH = {envdir}

[testenv:py35]
deps =
    flake8
    coverage == 5.5
    distro == 1.0.1
    Jinja2 == 2.8
    libsvm == 3.23.0.4
    MarkupSafe == 0.23
    natsort == 4.0.3
    opencv_python == 4.4.0.42
    psutil == 5.9.5
    requests == 2.9.1
    tqdm == 4.19.5
    urwid == 1.3.1
    pyparsing == 2.0.3
    PyYAML == 3.11
    XlsxWriter == 0.7.3
setenv=
# we do not care about the package version in tox
#  but it breaks some old python3.5 builds
    SETUPTOOLS_SCM_PRETEND_VERSION=0.0
    PROVIDERPATH = {envdir}
