name: checkbox-gpgpu-tools
summary: Tools used for the Checkbox GPGPU provider
version: 0.0.1
description: |
  This package contains the various programs that are used in the Checkbox GPGPU
  test suite.

  Included in this package are:
    * `cuda-samples`: Various test programs from NVIDIA.

base: core24
grade: stable
confinement: strict
compression: lzo

package-repositories:
  - type: apt
    architectures: [amd64]
    formats: [deb]
    path: /
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64

apps:
  device-query-drv:
    command: usr/share/doc/nvidia-cuda-toolkit/examples/Samples/1_Utilities/deviceQueryDrv/deviceQueryDrv
    plugs: [opengl]

  matrix-mul-drv:
    command: usr/share/doc/nvidia-cuda-toolkit/examples/Samples/0_Introduction/matrixMulDrv/matrixMulDrv
    plugs: [opengl]

  vector-add-drv:
    command: usr/share/doc/nvidia-cuda-toolkit/examples/Samples/0_Introduction/vectorAddDrv/vectorAddDrv
    plugs: [opengl]

  simple-texture-drv:
    command: usr/share/doc/nvidia-cuda-toolkit/examples/Samples/0_Introduction/simpleTextureDrv/simpleTextureDrv
    plugs: [opengl]

parts:
  glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-type: git
    source-subdir: glib-only
    plugin: make
    build-packages: [libglib2.0-dev]
    stage-packages: [libglib2.0-bin]

  cuda-samples:
    after: [glib-only]
    plugin: dump
    source: https://github.com/NVIDIA/cuda-samples.git
    source-type: git
    stage-packages: [libglu1-mesa]
    organize:
      Common/UtilNPP: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Common/data: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Common/*.cpp: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Common/*.h: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Common/*.hxx: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Samples: usr/share/doc/nvidia-cuda-toolkit/examples/Samples/
      Makefile: usr/share/doc/nvidia-cuda-toolkit/examples/
      README.md: usr/share/doc/nvidia-cuda-toolkit/examples/
      LICENSE: usr/share/doc/nvidia-cuda-toolkit/examples/
      CHANGELOG: usr/share/doc/nvidia-cuda-toolkit/examples/

  device-query-drv:
    plugin: nil
    after: [cuda-samples]
    build-packages: [cuda-toolkit-12-6]
    override-build: |
      make -C $CRAFT_STAGE/usr/share/doc/nvidia-cuda-toolkit/examples/Samples/1_Utilities/deviceQueryDrv

  matrix-mul-drv:
    plugin: nil
    after: [cuda-samples]
    build-packages: [cuda-toolkit-12-6]
    override-build: |
      make -C $CRAFT_STAGE/usr/share/doc/nvidia-cuda-toolkit/examples/Samples/0_Introduction/matrixMulDrv

  vector-add-drv:
    plugin: nil
    after: [cuda-samples]
    build-packages: [cuda-toolkit-12-6]
    override-build: |
      make -C $CRAFT_STAGE/usr/share/doc/nvidia-cuda-toolkit/examples/Samples/0_Introduction/vectorAddDrv

  simple-texture-drv:
    plugin: nil
    after: [cuda-samples]
    build-packages: [cuda-toolkit-12-6]
    override-build: |
      make -C $CRAFT_STAGE/usr/share/doc/nvidia-cuda-toolkit/examples/Samples/0_Introduction/simpleTextureDrv
