name: checkbox-gpgpu-tools
summary: Tools used for the Checkbox GPGPU provider
version: 0.0.1
description: |
  This package contains the various programs that are used in the Checkbox GPGPU
  test suite.

  Included in this package are:
    * `cuda-samples`: Various test programs from NVIDIA.

base: core24
grade: stable
confinement: strict
compression: lzo

package-repositories:
  - type: apt
    architectures: [amd64]
    formats: [deb]
    path: /
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64

apps:
  device-query-drv:
    command: bin/launcher
    environment:
      TEST_GROUP: 1_Utilities
      TEST_NAME: deviceQueryDrv
    plugs: [opengl]

  matrix-mul-drv:
    command: bin/launcher
    environment:
      TEST_GROUP: 0_Introduction
      TEST_NAME: matrixMulDrv
    plugs: [opengl]

  vector-add-drv:
    command: bin/launcher
    environment:
      TEST_GROUP: 0_Introduction
      TEST_NAME: vectorAddDrv
    plugs: [opengl]

  simple-texture-drv:
    command: bin/launcher
    environment:
      TEST_GROUP: 0_Introduction
      TEST_NAME: simpleTextureDrv
    plugs: [opengl]

parts:
  launcher:
    plugin: dump
    source: .
    source-type: local
    organize:
      launcher: bin/

  glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-type: git
    source-subdir: glib-only
    plugin: make
    build-packages: [libglib2.0-dev]
    stage-packages: [libglib2.0-bin]

  cuda-samples:
    after: [glib-only]
    plugin: dump
    source: https://github.com/NVIDIA/cuda-samples.git
    source-type: git
    stage-packages: [libglu1-mesa]
    organize:
      Common/UtilNPP: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Common/data: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Common/*.cpp: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Common/*.h: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Common/*.hxx: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Samples: usr/share/doc/nvidia-cuda-toolkit/examples/Samples/
      Makefile: usr/share/doc/nvidia-cuda-toolkit/examples/
      README.md: usr/share/doc/nvidia-cuda-toolkit/examples/
      LICENSE: usr/share/doc/nvidia-cuda-toolkit/examples/
      CHANGELOG: usr/share/doc/nvidia-cuda-toolkit/examples/

  device-query-drv:
    plugin: nil
    after: [cuda-samples]
    build-packages: [cuda-toolkit]
    build-environment:
      - GROUP_NAME: 1_Utilities
      - TEST_NAME: deviceQueryDrv
      - SAMPLES_PATH: usr/share/doc/nvidia-cuda-toolkit/examples/Samples
      - SRC_DIR: $CRAFT_STAGE/$SAMPLES_PATH/$GROUP_NAME/$TEST_NAME
      - DEST_DIR: $CRAFT_PART_INSTALL/$SAMPLES_PATH/$GROUP_NAME/$TEST_NAME
    override-build: |
      make -C $SRC_DIR
      mkdir -p $DEST_DIR
      cp $SRC_DIR/$TEST_NAME $DEST_DIR/

  matrix-mul-drv:
    plugin: nil
    after: [cuda-samples]
    build-packages: [cuda-toolkit]
    build-environment:
      - GROUP_NAME: 0_Introduction
      - TEST_NAME: matrixMulDrv
      - SAMPLES_PATH: usr/share/doc/nvidia-cuda-toolkit/examples/Samples
      - SRC_DIR: $CRAFT_STAGE/$SAMPLES_PATH/$GROUP_NAME/$TEST_NAME
      - DEST_DIR: $CRAFT_PART_INSTALL/$SAMPLES_PATH/$GROUP_NAME/$TEST_NAME
    override-build: |
      make -C $SRC_DIR
      mkdir -p $DEST_DIR
      cp $SRC_DIR/$TEST_NAME $DEST_DIR/
      cp -r $SRC_DIR/data $DEST_DIR/

  vector-add-drv:
    plugin: nil
    after: [cuda-samples]
    build-packages: [cuda-toolkit]
    build-environment:
      - GROUP_NAME: 0_Introduction
      - TEST_NAME: vectorAddDrv
      - SAMPLES_PATH: usr/share/doc/nvidia-cuda-toolkit/examples/Samples
      - SRC_DIR: $CRAFT_STAGE/$SAMPLES_PATH/$GROUP_NAME/$TEST_NAME
      - DEST_DIR: $CRAFT_PART_INSTALL/$SAMPLES_PATH/$GROUP_NAME/$TEST_NAME
    override-build: |
      make -C $SRC_DIR
      mkdir -p $DEST_DIR
      cp $SRC_DIR/$TEST_NAME $DEST_DIR/
      cp -r $SRC_DIR/data $DEST_DIR/

  simple-texture-drv:
    plugin: nil
    after: [cuda-samples]
    build-packages: [cuda-toolkit]
    build-environment:
      - GROUP_NAME: 0_Introduction
      - TEST_NAME: simpleTextureDrv
      - SAMPLES_PATH: usr/share/doc/nvidia-cuda-toolkit/examples/Samples
      - SRC_DIR: $CRAFT_STAGE/$SAMPLES_PATH/$GROUP_NAME/$TEST_NAME
      - DEST_DIR: $CRAFT_PART_INSTALL/$SAMPLES_PATH/$GROUP_NAME/$TEST_NAME
    override-build: |
      make -C $SRC_DIR
      mkdir -p $DEST_DIR
      cp $SRC_DIR/$TEST_NAME $DEST_DIR/
      cp -r $SRC_DIR/data $DEST_DIR/

lint:
  ignore:
    - library:
      - usr/lib/x86_64-linux-gnu/libGLU.so*
      - usr/lib/x86_64-linux-gnu/libOpenGL.so*
      - usr/lib/x86_64-linux-gnu/libGLdispatch.so*