name: checkbox-gpgpu-tools
summary: Tools used for the Checkbox GPGPU provider
version: 0.0.1
description: |
  This package contains the various programs that are used in the Checkbox GPGPU
  test suite.

  Included in this package are:
    * `checkbox-gpgpu-tools.gpu-burn`: GPU stress test based on CUDA toolkit.
    * `checkbox-gpgpu-tools.cuda-samples`: Various test programs from NVIDIA.
    * `checkbox-gpgpu-tools.rvs`: ROCm Validation Suite, a validation tool created by AMD for their GPUs.

base: core24
grade: stable
confinement: strict
compression: lzo

package-repositories:
  - type: apt
    architectures: [amd64]
    formats: [deb]
    path: /
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64
  - type: apt
    architectures: [amd64]
    components: [main]
    suites: [noble]
    key-id: CA8BB4727A47B4D09B4EE8969386B48A1A693C5C
    url: https://repo.radeon.com/amdgpu/6.2/ubuntu
  - type: apt
    architectures: [amd64]
    components: [main]
    suites: [noble]
    key-id: CA8BB4727A47B4D09B4EE8969386B48A1A693C5C
    url: https://repo.radeon.com/rocm/apt/6.2

apps:
  gpu-burn:
    command: usr/sbin/gpu_burn -c $SNAP/usr/share/gpu-burn/compare.ptx
    plugs:
      - opengl
      - nvidia-drivers-support
      - home

  rvs:
    command: rvs
    plugs: 
      - opengl
      - home

  device-query-drv:
    command: usr/share/doc/nvidia-cuda-toolkit/examples/Samples/1_Utilities/deviceQueryDrv/deviceQueryDrv
    plugs:
      - opengl
      - nvidia-drivers-support
      - home

  matrix-mul-drv:
    command: usr/share/doc/nvidia-cuda-toolkit/examples/Samples/0_Introduction/matrixMulDrv/matrixMulDrv
    plugs:
      - opengl
      - nvidia-drivers-support
      - home

  vector-add-drv:
    command: usr/share/doc/nvidia-cuda-toolkit/examples/Samples/0_Introduction/vectorAddDrv/vectorAddDrv
    plugs:
      - opengl
      - nvidia-drivers-support
      - home

  simple-texture-drv:
    command: usr/share/doc/nvidia-cuda-toolkit/examples/Samples/0_Introduction/simpleTextureDrv/simpleTextureDrv
    plugs:
      - opengl
      - nvidia-drivers-support
      - home

parts:
  rocm-validation-suite:
    plugin: nil
    stage-packages:
      - libnuma1
      - rocm-validation-suite

  gpu-burn:
    plugin: make
    source: https://github.com/wilicc/gpu-burn.git
    source-type: git
    build-packages: [cuda-toolkit-12-6]
    stage-packages: [libcublas-12-6]
    override-build: |
      make
      mkdir -p $CRAFT_PART_INSTALL/usr/sbin $CRAFT_PART_INSTALL/usr/share/gpu-burn
      cp gpu_burn $CRAFT_PART_INSTALL/usr/share/gpu-burn/
      cp compare.ptx $CRAFT_PART_INSTALL/usr/share/gpu-burn/
      ln -s ../share/gpu-burn/gpu_burn $CRAFT_PART_INSTALL/usr/sbin/gpu-burn

  cuda-samples:
    plugin: dump
    source: https://github.com/NVIDIA/cuda-samples.git
    source-type: git
    organize:
      Common/UtilNPP: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Common/data: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Common/*.cpp: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Common/*.h: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Common/*.hxx: usr/share/doc/nvidia-cuda-toolkit/examples/Common/
      Samples: usr/share/doc/nvidia-cuda-toolkit/examples/Samples/
      Makefile: usr/share/doc/nvidia-cuda-toolkit/examples/
      README.md: usr/share/doc/nvidia-cuda-toolkit/examples/
      LICENSE: usr/share/doc/nvidia-cuda-toolkit/examples/
      CHANGELOG: usr/share/doc/nvidia-cuda-toolkit/examples/

  device-query-drv:
    plugin: nil
    after: [cuda-samples]
    build-packages: [cuda-toolkit-12-6]
    override-build: |
      make -C $CRAFT_STAGE/usr/share/doc/nvidia-cuda-toolkit/examples/Samples/1_Utilities/deviceQueryDrv

  matrix-mul-drv:
    plugin: nil
    after: [cuda-samples]
    build-packages: [cuda-toolkit-12-6]
    override-build: |
      make -C $CRAFT_STAGE/usr/share/doc/nvidia-cuda-toolkit/examples/Samples/0_Introduction/matrixMulDrv

  vector-add-drv:
    plugin: nil
    after: [cuda-samples]
    build-packages: [cuda-toolkit-12-6]
    override-build: |
      make -C $CRAFT_STAGE/usr/share/doc/nvidia-cuda-toolkit/examples/Samples/0_Introduction/vectorAddDrv

  simple-texture-drv:
    plugin: nil
    after: [cuda-samples]
    build-packages: [cuda-toolkit-12-6]
    override-build: |
      make -C $CRAFT_STAGE/usr/share/doc/nvidia-cuda-toolkit/examples/Samples/0_Introduction/simpleTextureDrv
