[launcher]
stock_reports = text
local_submission = True

[test plan]
unit = 2021.com.canonical.certification::smoke-automated-passing
forced = True

[test selection]
forced = True

[ui]
type = silent

[exporter:json]
unit = com.canonical.plainbox::json

[transport:local_json]
type = file
path = ./submission.json

[report:local_json]
exporter = json
transport = local_json
forced = yes

[exporter:tar]
unit = com.canonical.plainbox::tar

[transport:local_tar]
type = file
path = ./submission.tar.xz

[report:local_tar]
exporter = tar
transport = local_tar
forced = yes
