name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report! Before submitting your issue, please make
        sure you have checked existing issues.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: >
        A clear and concise description of what the bug is.
        If applicable, add screenshots to help explain the problem you are facing.      
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: >
        Please provide a step-by-step instruction of how to reproduce the behavior.
      placeholder: |
        1. Launch Checkbox with command '...'
        2. Run job '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: >
        We need to know a bit more about the context in which you face the issue.
      placeholder: |
        - OS [e.g. UC20]:
        - Checkbox Type [Debian, Snap]:
        - Checkbox Version [e.g. 2.0.0]:
        - Hardware being tested (CPU, GPU, ...):
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: |
        - Checkbox session(s) (located in `/var/tmp/checkbox-ng/sessions/`, you usually want to select the most recent one)
        
        - logs from the impacted components (e.g. `lsblk` if this is related to an issue when testing a disk...); a safe option is to install and run `sosreport` to gather as much log as possible.
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context

