#!/usr/bin/env checkbox-cli
[launcher]
app_id = com.canonical.contrib:multimedia
launcher_version = 1

[test plan]
unit = com.canonical.contrib::multimedia-automated
forced = yes

[ui]
type = silent

[manifest]
com.canonical.contrib::has_hw_video_accel = true
com.canonical.contrib::has_vdpau = false
com.canonical.contrib::has_vulkan_video = false
com.canonical.contrib::has_nvdec = false
com.canonical.contrib::has_nvenc = false

[environment]
HW_VIDEO_ACCEL_VAAPI_DECODE = H.264:Main,High;H.265:Main;VP9:Profile 0;AV1:Main
HW_VIDEO_ACCEL_VAAPI_ENCODE = H.264:Main,High;H.265:Main;AV1:Main
