#!/bin/bash

function finish {
  rm -rf ./checkbox-ng
  rm -rf ./plainbox-provider-resource
}
trap finish EXIT

set -e

git clone git://git.launchpad.net/checkbox-ng
echo "I: running 'develop' on checkbox-ng"
( cd ./checkbox-ng/ && python3 setup.py develop --quiet | sed -e 's/^/I (develop output) /' )

git clone git://git.launchpad.net/plainbox-provider-resource
python3 ./plainbox-provider-resource/manage.py develop --force

./manage.py validate
