name: checkbox-oem
summary: Checkbox OEM test runner and public providers
description: "Checkbox OEM test runner and public providers"
confinement: strict
grade: stable
adopt-info: version-calculator

base: core26

plugs:
  checkbox-runtime:
    interface: content
    target: $SNAP/checkbox-runtime
    default-provider: checkbox26
  provider-resource:
    interface: content
    target: $SNAP/providers/checkbox-provider-resource
    default-provider: checkbox26
  provider-checkbox:
    interface: content
    target: $SNAP/providers/checkbox-provider-checkbox
    default-provider: checkbox26
  provider-tpm2:
    interface: content
    target: $SNAP/providers/checkbox-provider-tpm2
    default-provider: checkbox26
  provider-docker:
    interface: content
    target: $SNAP/providers/checkbox-provider-docker
    default-provider: checkbox26
  provider-certification-client:
    interface: content
    target: $SNAP/providers/checkbox-provider-certification-client
    default-provider: checkbox26
  # Legacy operation
  provider-ce-oem:
    interface: content
    target: $SNAP/providers/checkbox-provider-ce-oem

# Legacy operation
apps:
  checkbox-cli:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper
    plugs: &standard [home, network-bind, hardware-observe, bluez, bluetooth-control,
      gpio, modem-manager, mount-observe, network-manager, pulseaudio, serial-port,
      system-observe, tpm, timezone-control, timeserver-control]
  configure:
    command-chain: [bin/wrapper_local]
    command: bin/configure
  remote-slave:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper slave
    daemon: simple
    restart-condition: on-failure
    plugs: *standard
  shell:
    command-chain: [bin/wrapper_local]
    command: bin/shell-wrapper
    plugs: *standard
  test-runner:
    command-chain: [bin/wrapper_local]
    command: bin/test-runner
    plugs: *standard

passthrough:
  hooks:
    configure:
      command-chain: [bin/wrapper_local]

slots:
  provider-oem:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-oem
# Custom Frontend operation
  custom-frontend:
    interface: content
    content: custom-frontend
    read:
      - /

package-repositories:
  - type: apt
    ppa: checkbox-dev/edge # used to pull the installation machinery

parts:
  checkbox-provider-oem:
    plugin: dump
    source: checkbox-provider-oem
    source-type: local
    override-build: |
      export PYTHONPATH=/snap/checkbox26/current/lib/python3.14/site-packages/:/usr/lib/python3/dist-packages
      for path in $(find "/snap/checkbox26/current/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-oem --root="$CRAFT_PART_INSTALL"
    build-packages:
      - checkbox-ng
    build-snaps:
      - checkbox26
    stage-packages:
      - jq
  launchers:
    plugin: dump
    source: launchers/
    organize:
      '*': bin/
  config-variables:
    plugin: dump
    source: config/
  version-calculator:
    plugin: dump
    source: .
    override-pull: |
      craftctl default
      # version.txt created by prepare.sh
      export version=`cat $CRAFT_PART_SRC/version.txt`
      [ $version ] || exit 1
      craftctl set version=$version
    stage:
      - version.txt
