#!/usr/bin/env sh

venv_path=${1:-venv}

venv_path=$(realpath "$venv_path")

if [ -d "$venv_path" ]; then
    echo "$venv_path already exists"
    exit 1
fi

virtualenv --quiet --system-site-packages --python=python3 "$venv_path"

# To prevent https://www.shellcheck.net/wiki/SC1091
# shellcheck source=/dev/null
. "$venv_path"/bin/activate
python3 -m pip install -e .
pip install tqdm psutil

mkdir -p "$venv_path/share/plainbox-providers-1"
echo "export PROVIDERPATH=$venv_path/share/plainbox-providers-1" >> "$venv_path"/bin/activate
echo "set -gx PROVIDERPATH $venv_path/share/plainbox-providers-1" >> "$venv_path"/bin/activate.fish

echo "virtualenv with an empty provider database created at $venv_path"
echo "To activate your virtualenv run:"
if [ "$(basename "$SHELL")" = "fish" ]; then
    echo "$ . $venv_path/bin/activate.fish"
else
    echo "$ . $venv_path/bin/activate"
fi
