name: checkbox-ce-oem
summary: Checkbox CE OEM test runner and public providers for 22.04 classic
description: "Checkbox CE OEM test runner and public providers for 22.04 classic"
confinement: classic
grade: stable

version: '1.0-jammy'

base: core22

apps:
  checkbox-cli:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper
  configure:
    command-chain: [bin/wrapper_local]
    command: bin/configure
  remote-slave:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper slave
    daemon: simple
    restart-condition: on-failure
  shell:
    command-chain: [bin/wrapper_local]
    command: bin/shell-wrapper
  test-runner:
    command-chain: [bin/wrapper_local]
    command: bin/test-runner

passthrough:
  hooks:
    configure:
      command-chain: [bin/wrapper_local]

parts:
  checkbox-provider-ce-oem:
    plugin: dump
    source: https://github.com/canonical/checkbox-provider-ce-oem.git
    source-type: git
    stage-packages:
      - alsa-utils
      - mtd-utils
      - u-boot-tools
      - v4l-utils
      - device-tree-compiler
      - linuxptp
      - snmp
    override-prime: |
      snapcraftctl prime
      rm lib/systemd/system/alsa-utils.service
    override-build: |
      export PYTHONPATH=/snap/checkbox22/current/lib/python3.10/site-packages/
      for path in $(find "/snap/checkbox22/current/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      cd checkbox-provider-ce-oem
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-ce-oem --root="$SNAPCRAFT_PART_INSTALL"
    build-snaps:
      - checkbox22
    build-packages:
      - python3-dev
      - python3-jinja2
      - python3-packaging
      - python3-urwid
      - python3-xlsxwriter
      - python3-requests-oauthlib
  input-pcspkr:
    plugin: nil
    build-packages:
      - gcc
      - libc6-dev
    override-build: |
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/bin
      gcc ${SNAPCRAFT_PROJECT_DIR}/parts/checkbox-provider-ce-oem/src/checkbox-provider-ce-oem/src/input-pcspkr.c -o ${SNAPCRAFT_PROJECT_DIR}/parts/checkbox-provider-ce-oem/src/checkbox-provider-ce-oem/src/beep
      cp -v ${SNAPCRAFT_PROJECT_DIR}/parts/checkbox-provider-ce-oem/src/checkbox-provider-ce-oem/src/beep ${SNAPCRAFT_PART_INSTALL}/usr/bin/

  parts-meta-info:
    plugin: nil
    override-build: |
      snapcraftctl build
      for p in `ls -d ../../*`; do
          if [ -d $p/src ]; then
            (cd $p/src
                if [ -d $p/src/.git ]; then
                    (echo `basename $p`\: && git show --pretty=format:"%h%d %aN %ci%n%s%n" -q ; echo ) >> $SNAPCRAFT_PART_INSTALL/parts_meta_info
                fi # for additional `source-type` support, elif them here
            )
          fi
      done
    after: [checkbox-provider-ce-oem]
  launchers:
    plugin: dump
    source: launchers/
    build-attributes: [no-patchelf]
    organize:
      '*': bin/
  config-variables:
    plugin: dump
    source: config/
    build-attributes: [no-patchelf]
