#!/bin/bash

. $(dirname "$(realpath $BASH_SOURCE)")/wrapper_local

echo "$SNAP_NAME runtime shell, type 'exit' to quit the session"
exec bash --rcfile <(cat ~/.bashrc; echo 'PS1="(checkbox-shell) $PS1"')