[tox]
envlist = py35,py36,py38,py310,py312
skip_missing_interpreters = true
skipsdist=True

[testenv]
allowlist_externals = rm
commands =
    pip -q install ../../checkbox-ng
    rm -f /var/tmp/checkbox-providers-develop/checkbox-provider-resource.provider
    rm -f /var/tmp/checkbox-providers-develop/checkbox-provider-base.provider
    # Required because this provider depends on the resource and base providers
    {envpython} ../resource/manage.py develop
    {envpython} ../base/manage.py develop
    {envpython} manage.py validate
    {envpython} -m coverage run manage.py test
    {envpython} -m coverage report
    {envpython} -m coverage xml

[testenv:py35]
deps =
    flake8
    coverage == 5.5
setenv=
# we do not care about the package version in tox
#  but it breaks some old python3.5 builds
    SETUPTOOLS_SCM_PRETEND_VERSION=0.0

[testenv:py36]
deps =
    flake8
    coverage == 5.5

[testenv:py38]
deps =
    flake8
    coverage == 7.3.0

[testenv:py310]
deps =
    flake8
    coverage == 7.3.0

[testenv:py312]
deps =
    flake8
    coverage == 7.4.4
