#!/bin/bash

function finish {
  rm -rf ./plainbox-provider-snappy
}
trap finish EXIT

set -e

git clone git://git.launchpad.net/plainbox-provider-snappy
python3 ./plainbox-provider-snappy/plainbox-provider-snappy-resource/manage.py develop --force
python3 ./plainbox-provider-snappy/plainbox-provider-snappy/manage.py develop --force

./manage.py validate
