#!/bin/bash

function finish {
  rm -rf ./plainbox-provider-snappy
  rm -rf ./plainbox-provider-resource
}
trap finish EXIT

set -e

git clone git://git.launchpad.net/plainbox-provider-resource
python3 ./plainbox-provider-resource/manage.py develop --force

git clone git://git.launchpad.net/plainbox-provider-snappy
python3 ./plainbox-provider-snappy/manage.py develop --force

./manage.py validate
