#!/bin/sh

set -e

python3 setup.py develop --quiet | sed -e 's/^/I (develop output) /'

./plainbox/impl/providers/categories/manage.py validate -N
./plainbox/impl/providers/exporters/manage.py validate -N
./plainbox/impl/providers/manifest/manage.py validate -N
