name: Check formatting with Black
permissions:
  contents: read
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-with-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e
        with:
          options: "--check --diff --line-length 79 --extend-exclude '/vendor/'"
