name: Bump checkbox version

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'release increment'
        default: 'minor'
        type: choice
        options:
        - minor
        - major

jobs:
  Bumpversion:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -qq -y bumpversion devscripts
      - name: Checkout checkbox monorepo
        uses: actions/checkout@v3
      - name: Bump versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBEMAIL: robot@canonical.com
          DEBFULLNAME: Devices Certification Bot
        run: |
          tools/release/bumpversion.sh ${{ inputs.increment }}
