name: Checkbox Snap daily cross-builds

on:
  workflow_dispatch:
  workflow_call:

jobs:
  snap-runtime:
    strategy:
      fail-fast: false
      matrix:
        releases: [16]
        arch: [amd64, arm64, armhf]
        include:
          # confs built by the other workflow
          - releases: 20
            arch: armhf
          - releases: 18
            arch: armhf
    runs-on: ubuntu-20.04
    timeout-minutes: 1200 #20h, this will timeout sooner due to inner timeouts
    env:
      SERIES: series${{ matrix.releases }}
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
    name: Runtime ${{ matrix.releases }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Copy over the common files for series ${{ matrix.releases }}
        run: |
          cd checkbox-core-snap/
          sudo apt update && sudo apt install -qq -y python3-setuptools-scm
          ./prepare.sh $SERIES

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build (retries on fail)
        uses: Wandalen/wretry.action@master
        id: snapcraft
        with:
          attempt_limit: 5
          action: canonical/snapcraft-multiarch-action@v1
          with: |
            architecture: ${{ matrix.arch }}
            path: checkbox-core-snap/series${{ matrix.releases }}

      - uses: actions/upload-artifact@v4
        name: Upload logs on failure
        if: failure()
        with:
          name: runtime-build-log-${{ matrix.releases }}-${{ matrix.arch }}
          path: |
            /home/runner/.cache/snapcraft/log/
            /home/runner/.local/state/snapcraft/log/
            checkbox-core-snap/series${{ matrix.releases }}/checkbox*.txt

      - uses: actions/upload-artifact@v4
        name: Upload the snap as artifact
        with:
          name: runtime_snap${{ matrix.releases }}_${{ matrix.arch }}.snap
          path: checkbox-core-snap/series${{ matrix.releases }}/*.snap

      - name: Publish track
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: canonical/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: latest/edge

  snap-frontend:
    strategy:
      fail-fast: false
      matrix:
        type: [classic, uc]
        release: [16, 18, 20]
        arch: [armhf, amd64, arm64]
        exclude:
          # other arch built on self hosted runners by the other workflow
          - release: 18
            arch: amd64
          - release: 18
            arch: arm64
          - release: 20
            arch: amd64
          - release: 20
            arch: arm64
    runs-on: ubuntu-20.04
    timeout-minutes: 1200 #20h, this will timeout sooner due to inner timeouts
    name: Frontend ${{ matrix.type }}${{ matrix.release }} - ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Copy over the common files for series ${{ matrix.type }}${{ matrix.release }}
        run: |
          cd checkbox-snap/
          sudo apt update && sudo apt install -qq -y python3-setuptools-scm
          ./prepare_${{ matrix.type }}.sh series_${{ matrix.type }}${{ matrix.release }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build (retries on fail)
        uses: Wandalen/wretry.action@master
        id: snapcraft
        with:
          attempt_limit: 5
          action: canonical/snapcraft-multiarch-action@v1
          with: |
            architecture: ${{ matrix.arch }}
            path: checkbox-snap/series_${{ matrix.type }}${{ matrix.release }}

      - uses: actions/upload-artifact@v4
        name: Upload logs on failure
        if: failure()
        with:
          name: frontend-build-log-${{ matrix.type }}${{ matrix.release }}-${{ matrix.arch }}
          path: |
            /home/runner/.cache/snapcraft/log/
            /home/runner/.local/state/snapcraft/log/
            checkbox-snap/series_${{ matrix.type }}${{ matrix.release }}/checkbox*.txt

      - uses: actions/upload-artifact@v4
        name: Upload the snaps as artefacts
        with:
          name: frontend_snaps_${{ matrix.type }}${{ matrix.release }}_${{matrix.arch}}.snap
          path: ${{ steps.snapcraft.outputs.snap }}

      - name: Publish track
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: canonical/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          # channel is ucXX for uc snaps and XX.04 for classic snaps
          release: ${{ matrix.type == 'uc' && format('uc{0}', matrix.release) || format('{0}.04', matrix.release) }}/edge
