name: Daily builds
permissions:
  contents: read
  actions: read # used by gh api
on:
  push:
    branches:
      - release/16
  workflow_dispatch:

jobs:
  snap-cross-build-upload-daily:
    needs: check_for_commits
    uses: ./.github/workflows/checkbox-daily-cross-builds.yaml
    secrets:
      SNAPCRAFT7_CREDS: ${{ secrets.SNAPCRAFT7_CREDS }}
    with:
      store_upload: true
