name: Beta version of deb packages
run-name: Beta version of deb packages ${{ github.ref_name }}

on:
  push:
    tags:
        - "v*"
  workflow_dispatch:

jobs:
  Release:
    runs-on: [self-hosted, linux, large]
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -qq -y python3-launchpadlib
          git clone -b main https://git.launchpad.net/~hook25/ppa-dev-tools /tmp/ppa-dev-tools
      - name: Checkout checkbox monorepo
        uses: actions/checkout@v3
      - uses: Wandalen/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c # v1.3.0
        name: Import to LP, ask for a build and wait result
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDS }}
          PYTHONUNBUFFERED: 1
          CHECKBOX_REPO: ${{ github.repository }}
        with:
          attempt_delay: 600000 # 10min
          attempt_limit: 3
          command: |
            tools/release/release_deb_monorepo.py
      - name: Generate the github release note
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LP_CREDENTIALS: ${{ secrets.LP_CREDS }}
          CHECKBOX_REPO: ${{ github.repository }}
        run: |
          gh release create $(git describe --tags --abbrev=0 --match v*) -d --generate-notes
