name: Beta release notes
run-name: Beta release notes for ${{ github.ref_name }}

on:
  push:
    tags:
        - "v*"
  workflow_dispatch:

jobs:
  Release:
    runs-on: [self-hosted, linux, large]
    steps:
      - name: Setup the gh repository and install gh
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          gpg --fingerprint "2C6106201985B60E6C7AC87323F3D4EA75716059"
          sudo apt update -qq
          sudo apt install -y -qq gh
      - name: Generate the github release note
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LP_CREDENTIALS: ${{ secrets.LP_CREDS }}
          CHECKBOX_REPO: ${{ github.repository }}
        run: |
          gh release create $(git describe --tags --abbrev=0 --match v*) -d --generate-notes
