name: Test provider-sru with tox

on:
  push:
    branches: [ main ]
    paths:
      - providers/sru/**
  pull_request:
    branches: [ main ]
    paths:
      - providers/sru/**
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: providers/sru
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ["3.5", "3.6", "3.8", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
      - name: Run tox
        run: tox
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
