name: Validate unit YAML files

permissions:
  contents: read

on:
  push:
    paths:
      - '**/units/*.yaml'
      - '**/units/*/*.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/units/*.yaml'
      - '**/units/*/*.yaml'
  workflow_dispatch:

jobs:
  validate_unit_yaml:
    name: Validate unit YAML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Checkbox monorepo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
      - name: Install validate tool
        run: uv tool install ./unit_json_schema/validate
      - name: Validate unit YAML files
        run: |
          find . -path '*/units/**' -name "*.yaml" -print0 \
            | xargs -0 validate unit_json_schema/unit.schema.json
